# -*- coding: utf-8 -*-
"""activity3_Muhammad_Dzulfakor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIltCdxD24HZo1xqXuAP_s4CxhB6BkdQ

**Activity 1 – Eksperimen Tipe Data**
"""

nama = "Muhammad Dzulfakor"
umur = 19
ipk = 3.75
mahasiswa_aktif = True

print(nama)
print(umur)
print(ipk)
print(mahasiswa_aktif)
print(type(nama))
print(type(umur))
print(type(ipk))
print(type(mahasiswa_aktif))
print(len(nama))

"""**Activity 2 – Konversi Tipe Data**"""

nilai = 87.75

print(nilai)
print(type(nilai))

nilai_baru = int(nilai)

print(nilai_baru)
print(type(nilai_baru))

skor = 90
skor_teks = str(skor)

print("Nilai saya adalah " + skor_teks)
print(type(skor_teks))

berat = "65.5"
berat_baru = float(berat)

print(berat_baru)
print(type(berat_baru))
print(berat_baru + 2.5)